security:
    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: true

    acl:
        connection: default

    encoders:
        Sulu\Bundle\SecurityBundle\Entity\User:
            algorithm: sha512
            iterations: 5000
            encode_as_base64: false

    providers:
        sulu:
            id: sulu_security.user_repository

    access_control:
        - { path: ^/admin/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/security/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/_wdt, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: ROLE_USER }

    firewalls:
        oauth_token:
            pattern:    ^/admin/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/admin/oauth/v2/auth
            http_basic: true

        admin:
            pattern: ^/
            anonymous: ~
            fos_oauth:  true
            entry_point: sulu_security.authentication_entry_point
            form_login:
                login_path: sulu_admin.login
                check_path: sulu_admin.login_check
                success_handler: sulu_security.authentication_handler
                failure_handler: sulu_security.authentication_handler
            logout:
                path: /admin/logout
                target: /admin/
